# Generated by Django 4.0.4 on 2022-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(1, 'Redmi Phones'), (2, 'TV'), (3, 'Laptops'), (4, 'Fitness'), (5, 'Home'), (6, 'Audio')], default=1, max_length=20)),
            ],
        ),
    ]
