# Generated by Django 4.0.4 on 2022-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productmodel_image_alter_productcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
