# Generated by Django 4.0.4 on 2022-05-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productmodel_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
            ],
        ),
    ]
