# Generated by Django 4.0.4 on 2022-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='usr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
