# Generated by Django 4.0.4 on 2022-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_cartmodel_usr_cartmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='fkey',
            new_name='prdt',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='item',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
